import { test, expect } from '@playwright/test';

test.describe('prompt-to-video', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/');
  });

  test('should load the main page with all key elements', async ({ page }) => {
    // Verify header title
    await expect(page.locator('h1')).toContainText('Prompt-to-Video');
    
    // Verify "Your Concept" label is visible
    await expect(page.getByText('Your Concept').first()).toBeVisible();
    
    // Verify textarea has correct placeholder
    const textarea = page.getByPlaceholder('Describe your story idea...');
    await expect(textarea).toBeVisible();
    
    // Verify default prompt is pre-filled
    await expect(textarea).toHaveValue(/Create an inspiring video about leadership/i);
    
    // Verify Generate Story button is visible
    await expect(page.getByRole('button', { name: 'Generate Story', exact: true })).toBeVisible();
    
    // Verify Progress section
    await expect(page.getByText('Progress').first()).toBeVisible();
    
    // Verify welcome message in chat
    await expect(page.getByText(/Enter a prompt and generate your story/i)).toBeVisible();
  });

  test('should start generation and show loading state', async ({ page }) => {
    const textarea = page.getByPlaceholder('Describe your story idea...');
    const generateButton = page.getByRole('button', { name: 'Generate Story', exact: true });
    
    // Click generate button
    await generateButton.click();
    
    // Verify loading state appears - button shows "Generating..." and spinner
    await expect(page.getByRole('button', { name: 'Generating...', exact: true })).toBeVisible();
    
    // Verify textarea is disabled during generation
    await expect(textarea).toBeDisabled();
    
    // Verify generate button is disabled
    await expect(generateButton).toBeDisabled();
  });

  test('should generate story scenes and display video player', async ({ page }) => {
    // Start generation
    await page.getByRole('button', { name: 'Generate Story', exact: true }).click();
    
    // Wait for generation to complete - wait for scenes to be generated
    // The app generates 10 scenes (setup + conflict + climax + resolution)
    await page.waitForTimeout(5000); // Allow time for API calls
    
    // Verify the video player area has content - look for a character name in the scene
    // After generation, currentSceneIndex should be 0 and scenes array should have items
    const videoContainer = page.locator('.aspect-video');
    await expect(videoContainer).toBeVisible();
    
    // Check that scenes were generated by verifying chat messages show progress
    const chatMessages = page.locator('[class*="space-y-3"]');
    await expect(chatMessages).toBeVisible();
  });

  test('should allow re-generation with new prompt', async ({ page }) => {
    const textarea = page.getByPlaceholder('Describe your story idea...');
    const generateButton = page.getByRole('button', { name: 'Generate Story', exact: true });
    
    // Clear and enter new prompt
    await textarea.clear();
    await textarea.fill('A story about courage');
    
    // Click generate
    await generateButton.click();
    
    // Wait for generation
    await page.waitForTimeout(5000);
    
    // Verify new prompt is used (scenes should reflect new content)
    // The textarea should be enabled after generation completes
    await expect(textarea).toBeEnabled();
    
    // Generate button should be enabled again
    await expect(generateButton).toBeEnabled();
  });

  test('should navigate between scenes using keyboard', async ({ page }) => {
    // Generate story first
    await page.getByRole('button', { name: 'Generate Story', exact: true }).click();
    await page.waitForTimeout(5000);
    
    // Press right arrow to go to next scene
    await page.keyboard.press('ArrowRight');
    
    // Press left arrow to go back
    await page.keyboard.press('ArrowLeft');
    
    // Verify the scene container is still visible
    const videoContainer = page.locator('.aspect-video');
    await expect(videoContainer).toBeVisible();
  });

  test('should toggle play/pause with spacebar', async ({ page }) => {
    // Generate story first
    await page.getByRole('button', { name: 'Generate Story', exact: true }).click();
    await page.waitForTimeout(5000);
    
    // Press spacebar to play
    await page.keyboard.press('Space');
    
    // The app should respond (state changes internally)
    // Verify video container is still present
    const videoContainer = page.locator('.aspect-video');
    await expect(videoContainer).toBeVisible();
    
    // Press spacebar again to pause
    await page.keyboard.press('Space');
  });

  test('should display correctly on mobile viewport', async ({ page }) => {
    // Set mobile viewport
    await page.setViewportSize({ width: 375, height: 812 });
    
    // Verify header is visible
    await expect(page.locator('h1')).toContainText('Prompt-to-Video');
    
    // Verify input section is visible
    await expect(page.getByText('Your Concept').first()).toBeVisible();
    
    // Verify Generate button is visible and accessible
    const generateButton = page.getByRole('button', { name: 'Generate Story', exact: true });
    await expect(generateButton).toBeVisible();
    
    // Verify Progress section is visible on mobile
    await expect(page.getByText('Progress').first()).toBeVisible();
  });

  test('should toggle mute state', async ({ page }) => {
    // Find and click the mute toggle button (VolumeX or Volume2 icon)
    const muteButton = page.locator('button').filter({ has: page.locator('svg') }).first();
    
    // The mute button should be present in the header
    const headerButtons = page.locator('header button');
    await expect(headerButtons.first()).toBeVisible();
  });
});